-- Theater seed data (338 theaters)
-- Paste into the Supabase SQL editor and run.
INSERT INTO theaters (name, city, state, audition_page_url, notes) VALUES
  ('3-D Theatrics', 'Long Beach', 'CA', 'https://www.3dtheatricals.org/auditions/', 'No housing or transportation provided'),
  ('5th Ave Theatre', 'Seattle', 'WA', 'https://www.5thavenue.org/about/careers/auditions/', ''),
  ('7 Angels Theatre', 'Waterbury', 'CT', 'https://www.7atheatre.org/work-with-us', ''),
  ('Act 2 Playhouse', 'Ambler', 'PA', 'https://act2.org/about/casting/', ''),
  ('Actors Theatre of Indiana', 'Carmel', 'IN', 'http://atistage.org/auditions/', ''),
  ('Actors'' Playhouse at the Miracle Theatre', 'Coral Gables', 'FL', 'https://www.actorsplayhouse.org/auditions/', ''),
  ('Actors'' Repertory Theatre of Simi', 'Simi Valley', 'CA', NULL, ''),
  ('AD Players', 'Houston', 'TX', 'https://www.adplayers.org/audition', ''),
  ('Alabama Shakespeare Festival', 'Montgomery', 'AL', 'https://asf.net/auditions/', ''),
  ('Algonquin Arts Center', 'Manasquan', 'NJ', 'http://www.algonquinarts.com/auditions.php', ''),
  ('Alhambra Theatre and Dining', 'Jacksonville', 'FL', NULL, 'Equity-but can send in stuff'),
  ('Alluvion Stage Company', 'Lynchburg', 'VA', NULL, ''),
  ('Alpine Theatre Project', 'Whitefish', 'MT', 'https://atpwhitefish.org/jobs-auditions', 'internships by invitation only'),
  ('Altarena Playhouse', 'Alameda', 'CA', 'https://www.altarena.org/2020-auditions', ''),
  ('Amarillo Opera', 'Amarillo', 'TX', 'https://www.amarilloopera.org/', ''),
  ('American Stage Theatre', 'St. Petersburg', 'FL', NULL, ''),
  ('Annapolis Opera', 'Annapolis', 'MD', 'http://annapolisopera.org/auditions/', ''),
  ('Arena Stage DC', 'Washington', 'DC', 'https://www.arenastage.org/opportunities/', ''),
  ('Arizona Broadway Theatre', 'Peoria', 'AZ', 'https://azbroadway.org/about-us/employment-auditions-internships/', ''),
  ('Arizona Theatre Company', 'Tucson', 'AZ', 'https://arizonatheatre.org/auditions-submissions/', ''),
  ('Arkansas Rep', 'Little Rock', 'AR', 'https://www.therep.org/work-with-us/', ''),
  ('Arrow Rock Lyceum Theatre', 'Arrow Rock', 'MO', 'http://lyceumtheatre.org/about/auditions/', ''),
  ('ArtisTree Music Theatre Festival- The Grange Theatre', 'Promfret', 'VT', 'https://artistreevt.org/auditions/', ''),
  ('Arvada Center for the Arts', 'Arvada', 'CO', 'https://arvadacenter.org/theatre/auditions', ''),
  ('Athens Theatre', 'Deland', 'FL', 'https://athensdeland.com/auditions/', ''),
  ('Barn Theatre School', 'Augusta', 'MI', 'https://barntheatreschool.org/professional-theatre-auditions-apprenticeship/', 'EMC program'),
  ('Barter Theatre', 'Abingdon', 'VA', NULL, ''),
  ('BDT Stage', 'Boulder', 'CO', 'https://bdtstage.com/backstage/auditions-jobs/', ''),
  ('Beck Center for the Arts', 'Lakewood', 'OH', 'http://www.beckcenter.org/what-we-do/theater/auditions/', ''),
  ('Beef & Boards Dinner Theatre', 'Indianapolis', 'IN', NULL, ''),
  ('Berkeley Playhouse', 'Berkeley', 'CA', 'https://tickets.berkeleyplayhouse.org/online/default.asp?doWork::WScontent::loadArticle=Load&BOparam::WScontent::loadArticle::article_id=E4A4CA22-72D6-41CE-97EE-3014A7FEF17F&menu_id=3CD3099C-E1FA-45ED-8066-9C7856768BBA', ''),
  ('Berkshire Theatre Group', 'Pittsfield', 'MA', 'https://www.berkshiretheatregroup.org/shrek-the-musical-audition-call/', 'Acting Internship'),
  ('Big Arts Sanibel Island', 'Sanibel Island', 'FL', NULL, 'BIG ARTS'),
  ('Big Nosie Theatre', 'Des Plaines', 'IL', NULL, ''),
  ('BigFork Summer Theatre', 'Bigfork', 'MT', NULL, ''),
  ('Bluff City Theatre', 'Hannibal', 'MO', 'http://bluffcitytheater.com/auditions-at-bluff-city-theater-this-weekend-dont-miss-your-chance/', ''),
  ('Bristol Riverside Theatre', 'Bristol', 'PA', 'https://www.brtstage.org/employment-opportunities/', ''),
  ('Broadway Palm Dinner Theatre', 'Fort Myers', 'FL', 'http://broadwaypalm.com/backstage/auditions/', ''),
  ('Broadway Rose Theatre Company', 'Tigard', 'OR', 'https://www.broadwayrose.org/auditions', ''),
  ('Broadway Theatre of Pitman', 'Pitman', 'NJ', 'https://www.thebroadwaytheatre.org/auditions/', 'Housing?'),
  ('Cabrillo Music Theatre', 'Thousand Oaks', 'CA', 'https://www.cabrillostage.com/auditions', 'No housing'),
  ('Cain Park', 'Cleveland Heights', 'OH', 'https://www.cainpark.com/241/Performance', ''),
  ('Cape Fear Regional Theatre', 'Fayetteville', 'NC', NULL, ''),
  ('Capitol Repertory Theatre', 'Albany', 'NY', 'https://capitalrep.org/auditions/', ''),
  ('Cardinal Stage Company', 'Bloomington', 'IN', 'https://cardinalstage.org/about-us/auditions/', ''),
  ('Carousel Music Theatre', 'Boothbay Harbor', 'ME', 'https://www.carouselmusictheater.org/auditions.html', ''),
  ('Casa Manana Theatre', 'Fort Worth', 'TX', 'http://www.casamanana.org/about/auditions/', ''),
  ('Cedar Summerstock Theater', 'Ansgar', 'IA', 'https://www.cedarsummerstock.org/auditions', ''),
  ('Cedar Summerstock Theatre', 'Ansgar', 'IA', NULL, ''),
  ('Chanhassen Dinner Theatre', 'Chanhassen', 'MN', NULL, ''),
  ('Charleston Stage', 'Charleston', 'NC', NULL, ''),
  ('Charlottsville Opera', 'Charlottesville', 'VA', 'https://www.charlottesvilleopera.org/chorus.html', ''),
  ('Chenango River Theatre', 'Greene', 'NY', 'http://www.chenangorivertheatre.org/Chenango_River_Theatre/Auditions_Jobs.html', 'Acting only'),
  ('Cincinnati Playhouse in the Park', 'Cincinnati', 'OH', 'https://www.cincyplay.com/employment', ''),
  ('Circa21 Dinner Playhouse', 'Rock Island', 'IL', 'http://www.circa21.com/auditions', ''),
  ('City Springs Theatre Company', 'Sandy Springs', 'GA', 'https://www.cityspringstheatre.com/auditions/', ''),
  ('Clinton Area Showboat Theatre', 'Clinton', 'IA', 'https://www.clintonshowboat.com/audition-information', ''),
  ('Coeur d'' Alene Summer Theatre', 'Coeur''d Alene', 'ID', 'http://www.cdasummertheatre.com/auditions.html', ''),
  ('Colorado Theatre Guild', '', 'CO', NULL, ''),
  ('Conwell''s Dinner Theatre', 'Marshall', 'MI', 'https://www.turkeyville.com/dinner-theatre/casting-and-employment/', ''),
  ('Cortland Rep Theatre', 'Cortland', 'NY', 'https://www.cortlandrep.org/employment/', ''),
  ('Covedale Center for the Performing Arts', 'Cincinnati', 'OH', 'http://www.cincinnatilandmarkproductions.com/ccpa/Auditions.aspx', ''),
  ('CPCC Summer Theatre Auditions', 'Charlotte', 'NC', 'http://blogs.cpcc.edu/theatre/auditions/cpcc-summer-theatre-auditions/', ''),
  ('Crane River Theatre', 'Kearney', 'NE', NULL, ''),
  ('Creede Rep Theatre', 'Creede', 'CO', 'https://creederep.org/work-with-us/job-opportunities/', ''),
  ('Cumberland County Playhouse', 'Crossville', 'TN', NULL, ''),
  ('Cumberland Theatre', 'Cumberland', 'MD', NULL, ''),
  ('Cupcake Theatre', 'Los Angles', 'CA', 'https://www.facebook.com/pg/CupcakeTheater/events/?ref=page_internal', ''),
  ('Cygnet Theatre', 'San Diego', 'CA', 'http://www.cygnettheatre.com/about/jobs.php', ''),
  ('Dallas Theatre Center', 'Dallas', 'TX', 'https://dallastheatercenter.org/auditions/', ''),
  ('Denver Center for the Performing Arts', 'Denver', 'CO', 'https://www.denvercenter.org/about-us/careers', ''),
  ('Derby Dinner Playhouse', 'Clarksville', 'IN', 'https://derbydinner.com/auditions/', ''),
  ('Downtown Cabaret Theatre', 'Bridgeport', 'CT', 'https://dtcab.com/auditions/', ''),
  ('Dreamcatcher Rep', 'Summit', 'NJ', 'http://www.dreamcatcherrep.org/casting', 'Equity, but some Non-Equity'),
  ('Drury Lane Theatre', 'Oakbrook Terrace', 'IL', 'http://www.drurylaneoakbrook.com/facility/contact-us/auditions', ''),
  ('Dutch Apple Dinner Theatre', 'Lancaster', 'PA', 'https://dutchapple.com/backstage/auditions/', ''),
  ('East Lyme Regional Theatre', 'Niantic', 'CT', 'https://www.eastlymeregionaltheater.com/audition-notice', ''),
  ('Encore Musical Theatre Festival', 'Dexter', 'MI', 'https://www.theencoretheatre.org/auditions/', ''),
  ('Engeman Theatre', 'Northport', 'NY', 'https://www.engemantheater.com/auditions', ''),
  ('Ensemble Stage', 'Banner Elk', 'NC', 'http://www.ensemblestage.com/auditions.html', 'Acting Only'),
  ('Ensemble Theatre of Cincinnati', 'Cincinnati', 'OH', NULL, ''),
  ('Exit 86 Theatre', 'Elmira', 'NY', 'https://www.exit82theatre.com/', ''),
  ('Farmers Alley Theatre', 'Kalamazoo', 'MI', 'http://www.farmersalleytheatre.com/auditions', ''),
  ('Festival  56', 'Princeton', 'IL', 'http://www.festival56.com/employment', ''),
  ('Finger Lakes Musical Theatre Festival', 'Auburn', 'NY', NULL, ''),
  ('Firehouse Center for the Arts', 'Newburyport', 'MA', 'https://www.firehouse.org/auditions/', ''),
  ('Fireside Theatre', 'Fort Atkinson', 'WI', 'http://www.firesidetheatre.com/', 'On Backstage'),
  ('Flat Rock Playhouse', 'Flat Rock', 'NC', 'https://www.flatrockplayhouse.org/youth-auditions', ''),
  ('Florida Repertory Theatre', 'Fort Myers', 'FL', 'https://www.floridarep.org/about-florida-rep/casting-calls/', ''),
  ('Florida Studio Theatre', 'Sarasota', 'FL', 'https://www.floridastudiotheatre.org/casting-and-hiring', 'Equity with non-equity internships'),
  ('Fort Peck Summer Theatre', 'Fort Peck', 'MT', 'https://www.fortpecktheatre.org/auditions', ''),
  ('Four Corners Musical Theatre', 'Farmington', 'NM', NULL, ''),
  ('Four Seasons Theatre', 'Madison', 'WI', 'http://fourseasonstheatre.com/auditions/', ''),
  ('Fulton Theatre', 'Lancaster', 'PA', 'http://www.thefulton.org/about/auditions/', ''),
  ('Garden Theatre', 'Winter Garden', 'FL', 'http://www.gardentheatre.org/get-involved/audition/', 'no housing'),
  ('Garland Summer Musicals', 'Garland', 'TX', NULL, ''),
  ('Garland Theatre', 'Garland', 'TX', 'https://www.garlandsummermusicals.org/index.php/season-schedule/auditions', ''),
  ('Gateway Playhouse', 'Somers Point', 'NJ', 'http://www.gatewaybythebay.org/', ''),
  ('Glow Lyric Theatre', 'Greenville', 'SC', 'http://glowlyric.com/about-us-2/auditions/', ''),
  ('Goodman Theatre', 'Chicago', 'IL', 'http://www.goodmantheatre.org/About/Auditions/', 'Acting Only'),
  ('Granbury Theatre Company', 'Granbury', 'TX', NULL, ''),
  ('Great Lakes Theatre', 'Cleveland', 'OH', 'http://www.greatlakestheater.org/work-with-us/auditions', ''),
  ('Great Plains Theatre', 'Abilene', 'KS', 'http://www.greatplainstheatre.com/auditions', ''),
  ('Greater Ocean City Company', 'Ocean City', 'NJ', 'http://oceancitytheatrecompany.com/about/casting/', ''),
  ('Greenbrier Valley Theatre', 'Lewisburg', 'WV', 'https://www.gvtheatre.org/educationauditions', ''),
  ('Greenville Theatre', 'Greenville', 'SC', NULL, 'local actors only'),
  ('Gretna Theatre', 'Mount Gretna', 'PA', NULL, ''),
  ('Gulfshore Playhouse', 'Naples', 'FL', 'https://www.gulfshoreplayhouse.org/summer-2017-auditions/', 'Plays Only'),
  ('Hale Center Theatre Orem', 'Orem', 'UT', 'http://www.haletheater.org/theater/auditions/', ''),
  ('Hale Centre Theatre', 'Sandy', 'UT', 'https://www.haletheatrearizona.com/Online/default.asp?BOparam::WScontent::loadArticle::permalink=auditions&BOparam::WScontent::loadArticle::context_id=', ''),
  ('Hanger Theatre', 'Ithaca', 'NY', NULL, ''),
  ('Hanover Theatre', 'Worcester', 'MA', 'https://thehanovertheatre.org/auditions.php', ''),
  ('Harbor Stage Company', 'Wellfleet', 'MA', NULL, ''),
  ('Heritage Theatre', 'Perry', 'UT', 'https://www.heritagetheatreutah.com/auditions', ''),
  ('Highland Summer Theatre', 'Mankato', 'MN', NULL, ''),
  ('Hillbarn Theatre', 'Foster City', 'CA', NULL, ''),
  ('Hippodrome Theatre', 'Gainesville', 'FL', 'https://thehipp.org/auditions/', 'Equity but non-eq can apply'),
  ('Hope Rep Theatre', 'Holland', 'MI', 'https://www.facebook.com/hopesummertheatre/', 'On Facebook, Broadway World'),
  ('Hunterdon Hills Playhouse', 'Hampton', 'NJ', 'http://www.hhplayhouse.com/index.php?src=gendocs&ref=Contact', 'On Backstage'),
  ('Huntington Theatre Company', 'Boston', 'MA', 'https://www.huntingtontheatre.org/auditions/', ''),
  ('Idaho Shakespeare Festival', 'Boise', 'ID', NULL, ''),
  ('Inland Valley Repertory Theatre', 'Claremont', 'CA', 'https://www.ivrt.org/audition', ''),
  ('Interlakes Summer Theatre', 'Meredith', 'NH', NULL, ''),
  ('Iron Bridge Theatre', 'Tyrone', 'PA', NULL, ''),
  ('Ivoryton Playhouse', 'Ivoryton', 'CT', 'http://www.ivorytonplayhouse.org/get-involved', ''),
  ('Jean''s Playhouse', 'Lincoln', 'NH', NULL, ''),
  ('Jefferson Performing Arts Society', 'Metairie', 'LA', NULL, ''),
  ('Jewel Theatre Company', 'Santa Cruz', 'CA', 'https://www.jeweltheatre.net/auditions/', ''),
  ('Judson Theatre Company', 'Southern Pines', 'North Carolina', 'https://judsontheatre.com/contact-us/', ''),
  ('Kalamazoo Civic Theatre', 'Kalamazoo', 'MI', 'https://www.kazoocivic.com/auditions', ''),
  ('Kansas City Rep Theatre', 'Kansas City', 'MO', 'https://opportunities.kcrep.org/auditions/', ''),
  ('Kansas City Starlight Theatre', 'Kansas City', 'MO', 'http://www.kcstarlight.com/broadway/auditions.aspx', 'Equity'),
  ('Keegan Theatre', 'Washington', 'DC', NULL, ''),
  ('Kincaid Regional Theatre', 'Falmouth', 'KY', 'https://www.krtshows.com/auditions', ''),
  ('La Comedia Dinner Theatre', 'Springboro', 'OH', 'https://lacomedia.com/audition-info/', ''),
  ('Lake City Playhouse', 'Coeur''d Alene', 'ID', 'http://www.lakecityplayhouse.org/auditions', ''),
  ('Lakewood Center for the Arts', 'Lake Oswego', 'OR', 'https://lakewood-center.org/theatre/auditions/', ''),
  ('Leavenworth Summer Theatre', '', '', 'https://leavenworthsummertheater.org/auditions', ''),
  ('Lees-McRae Summer Theatre', 'Banner Elk', 'NC', NULL, ''),
  ('Legendary Theatre', 'Redlands', 'CA', NULL, ''),
  ('Little Theatre on the Square', 'Sullivan', 'IL', 'http://www.thelittletheatre.org/contact-us/auditions/', ''),
  ('Lost Nation Theatre', 'Montpelier', 'VT', 'https://lostnationtheater.org/auditions-and-employment.html', ''),
  ('Lyric Stage of Boston', 'Boston', 'MA', NULL, 'no housing'),
  ('Lyric Theatre of Oklahoma', 'Oklahoma City', 'OK', 'http://www.lyrictheatreokc.com/about-the-lyric/auditions', ''),
  ('Mac-Haydn Theatre', 'Chatham', 'NY', 'http://www.machaydntheatre.org/', ''),
  ('Maine State Music Theatre', 'Brunswick', 'ME', NULL, ''),
  ('Maltz Jupiter Theatre', 'Jupiter', 'FL', 'https://www.jupitertheatre.org/2223-auditions', ''),
  ('Maples Repertory Theatre', 'Macon', 'MO', 'http://maplesrep.com/about/work-with-us/', ''),
  ('Marriott Theatre', 'Lincolnshire', 'IL', 'http://www.marriotttheatre.com/employment-and-auditions', ''),
  ('Mason Street Warehouse', 'Saugatuck', 'MI', 'https://sc4a.org/msw/', ''),
  ('McCoy Rigby Entertainment', 'Yorba Linda', 'CA', 'https://www.florescasting.com/auditions', ''),
  ('Mcleod Summer Playhouse', 'Carbondale', 'IL', NULL, ''),
  ('Media Theatre', 'Media', 'PA', 'https://mediatheatre.org/special-events/calendar/jan6and7auditions/', ''),
  ('Medow Brook Theatre', 'Rochester Hills', 'MI', 'http://www.mbtheatre.com/auditions/', ''),
  ('Mill Mountain Playhouse', 'Roanoke', 'VA', NULL, ''),
  ('Millbrook Playhouse', 'Mill Hall', 'PA', NULL, ''),
  ('Milton Theatre', 'Milton', 'DE', 'https://www.miltontheatre.com/auditions', ''),
  ('Milwaukee Rep Theatre', 'Milwaukee', 'WI', 'https://www.milwaukeerep.com/about/work-us/professional-residencies/', 'Acting Internship, plays only'),
  ('Miners Alley Playhouse', 'Golden', 'Colorado', 'https://minersalley.com/about/auditions/', ''),
  ('Montgomery Theatre', 'Souderton', 'PA', 'https://www.montgomerytheater.org/opportunities', 'no housing'),
  ('Mountain Play', 'Mill Valley', 'CA', NULL, ''),
  ('Mountain Theatre Company', 'Highlands', 'NC', 'https://www.mountaintheatre.com/auditions', ''),
  ('MTH Theatre at Crown Center', 'Kansas City', 'MO', 'https://musicaltheaterheritage.com/auditions/', ''),
  ('Music Theatre of Wichita', 'Wichita', 'KS', 'https://mtwichita.org/audition/audition-opportunities/', ''),
  ('Music Theatre Works', 'Wilmette', 'IL', 'https://www.musictheaterworks.com/auditions/', ''),
  ('Musical Theatre West', 'Long Beach', 'CA', 'http://musical.org/auditions/', ''),
  ('Myers Dinner Theatre', 'Hillsboro', 'IN', 'https://myersdt.com/theatre-employment', ''),
  ('Nashville Rep', 'Nashville', 'TN', 'https://nashvillerep.org/audition', ''),
  ('Nettle Creek Players', 'Hangerstown', 'IN', 'https://www.nettlecreekplayers.com/silnet-auction', ''),
  ('New Bedford Theatre Festival', 'New Bedford', 'MA', NULL, ''),
  ('New Century Theatre', 'Northampton', 'MA', 'http://www.newcenturytheatre.org/audition.html', 'Plays Only'),
  ('New Hampshire Professional Theatre Association', 'Manchester', 'NH', 'https://nhpta.org/auditions/', ''),
  ('New London Barn Theatre', 'New London', 'NH', 'https://www.nlbarn.org/jobs', ''),
  ('New Repertory Theatre', 'Watertown', 'MA', 'http://www.newrep.org/', ''),
  ('New Stage Theatre', 'Jackson', 'MS', 'http://newstagetheatre.com/about/employment/auditions-2/', ''),
  ('New Theatre & Restaurant', 'Overland Park', 'KS', 'https://newtheatre.com/job-opportunities/', ''),
  ('NextStop Theatre Company', 'Herndon', 'VA', NULL, ''),
  ('No Name Players', 'Pittsburgh', 'PA', 'http://www.nonameplayers.org/', ''),
  ('No Square Theatre', 'Laguna Beach', 'CA', NULL, ''),
  ('North Carolina Theatre', 'Raleigh', 'NC', NULL, ''),
  ('North Coast Repertory Theatre', 'Solana Beach', 'CA', 'https://northcoastrep.org/about-north-coast-repertory-theatre/casting/', ''),
  ('North Hampton Community College Summer Theatre', 'Bethlehem', 'PA', NULL, ''),
  ('North Shore Music Theatre', 'Beverly', 'MA', 'https://www.nsmt.org/auditions.html', ''),
  ('Northern Stage', 'White River Junction', 'VT', 'https://northernstage.org/employment-auditions/', 'Equity but non-eq can apply'),
  ('Ogden Musical Theatre', 'Ogden', 'Utah', 'https://ogdenmusicaltheatre.org/summerMusical/audition-info', ''),
  ('Ogunquit Playhouse', 'Ogunquit', 'ME', 'http://www.ogunquitplayhouse.org/auditions/', ''),
  ('Olney Theatre Company', 'Olney', 'MD', 'https://www.olneytheatre.org/', ''),
  ('Opera North', 'Lebanon', 'NH', 'https://operanorth.org/', ''),
  ('Ordway Theatre', 'St Paul', 'MN', 'https://ordway.org/about/employment/auditions/', ''),
  ('Oregon Cabaret Theatre', 'Ashland', 'OR', 'https://theoregoncabaret.com/backstage/casting/', ''),
  ('Orlando Rep Theatre', 'Orlando', 'FL', 'https://www.orlandorep.com/get-involved/auditions/', ''),
  ('Ozark Actors Theatre', 'Rolla', 'MO', NULL, ''),
  ('P3 Theatre Company', 'Long Beach', 'CA', NULL, ''),
  ('Pacific Coast Repertory Theatre', 'Pleasanton', 'CA', 'http://pcrtproductions.org/casting/', ''),
  ('Pagosa Springs Center for the Arts', 'Pagosa Springs', 'CO', 'http://pagosacenter.org/auditions-submissions-employment-internships-volunteers/auditions/', ''),
  ('Palm Canyon Theatre', 'Palm Springs', 'CA', NULL, ''),
  ('Parallel 45 Theatre Festival', 'Traverse City', 'MI', 'http://www.parallel45.org/opportunities/', ''),
  ('Paramount Theatre', 'Aurora', 'IL', 'https://paramountaurora.com/opportunities/auditions/', ''),
  ('Park Playhouse', 'Albany', 'NY', 'http://www.parkplayhouse.com/audition/', ''),
  ('Peach State Summer Theatre', 'Valdosta', 'GA', NULL, ''),
  ('Pennsylvania Shakespeare Festival', 'Allentown', 'PA', 'http://www.pashakespeare.org/psf_jobs.php', ''),
  ('Pentagle Arts', 'Woodstock', 'VT', NULL, ''),
  ('People''s Light', 'Malvern', 'PA', 'https://www.peopleslight.org/about/careers-opportunities/', ''),
  ('Peregrine Theatre Ensemble', 'Provincetown', 'Ma', NULL, ''),
  ('Peterborough Players', 'Peterborough', 'NH', 'https://www.peterboroughplayers.org/auditions.html', ''),
  ('Phoenix Theatre', 'Phoenix', 'AZ', 'https://www.phoenixtheatre.com/about-us/audition-callback-and-casting-information', ''),
  ('Phoenix Theatre', 'Indianapolis', 'IN', 'https://www.phoenixtheatre.org/work-with-us', ''),
  ('Pickleville Playhouse', 'Garden City', 'UT', 'https://www.picklevilleplayhouse.com/auditions', ''),
  ('Pines Dinner Theatre', 'Perform at the Pines - Pines Dinner Theatre - Allentown', 'PA', NULL, ''),
  ('Pittsburgh CLO', 'Pittsburgh', 'PA', 'http://www.pittsburghclo.org/pages/clo_auditions', ''),
  ('Pittsburgh Musical Theatre', 'Pittsburgh', 'PA', NULL, ''),
  ('Pittsburgh Playhouse', 'Pittsburgh', 'PA', 'http://www.pittsburghplayhouse.com/news/auditions', ''),
  ('Playmakers Rep Company', 'Chapel Hill', 'NC', 'https://www.playmakersrep.org/about-us/auditions/', 'Mostly Plays'),
  ('Plaza Theatrics', 'Bellmore', 'NY', 'https://plazatheatrical.com/about-us/job-opportunities/', ''),
  ('Porchlight Music Theatre', 'Chicago', 'IL', 'https://porchlightmusictheatre.org/about/opportunity/', ''),
  ('Porthouse Theatre', 'Cuyahoga Falls', 'OH', 'https://www.kent.edu/porthouse/auditions', ''),
  ('Post Playhouse', 'Harrison', 'NE', 'http://postplayhouse.com/industry-professionals/', ''),
  ('Prima Theatre', 'Lancaster', 'PA', NULL, ''),
  ('Queensbury Theatre', 'Houston', 'TX', 'https://www.queensburytheatre.org/auditions', ''),
  ('Ray of Light Theatre', 'San Francisco', 'CA', NULL, ''),
  ('Reagle Music Theatre', 'Waltham', 'MA', 'https://www.reaglemusictheatre.org/auditions-and-employment', ''),
  ('Red Barn Summer Theatre', 'Clinton County', 'IN', NULL, ''),
  ('Red Barn Theatre', 'Key West', 'FL', NULL, ''),
  ('Red Mountain Theatre Company', 'Brimingham', 'AL', 'http://redmountaintheatre.org/auditions/', ''),
  ('Regional Theatre of the Palouse', 'Auditions - RTOP Theatre - Pullman', 'WA', NULL, ''),
  ('Repertory Theatre of St. Louis', 'Webster Groves', 'MO', 'http://www.repstl.org/auditions/', 'Acting Only'),
  ('Riverside Center for the Performing Arts', 'Fredericksburg', 'VA', 'https://www.riversidedt.com/auditions/', ''),
  ('Rochester Opera House', 'Rochester', 'NY', 'http://www.rochesteroperahouse.com/auditions--employment.html', ''),
  ('Rocky Mountain Rep Theatre', 'Grand Lake', 'CO', 'http://www.rockymountainrep.com/about-rmrt/audition-for-us/', ''),
  ('Round Barn Theatre', 'Nappanee', 'IN', NULL, ''),
  ('Saint Michael''s Playhouse', 'Colchester', 'VT', 'https://saintmichaelsplayhouse.org/get-involved/casting/', 'Equity but non-eq can apply'),
  ('Salt Lake Acting Company', 'Salt Lake City', 'UT', NULL, ''),
  ('San Antonio Broadway Theatre', 'San Antonio', 'TX', 'https://sabroadwaytheatre.com/auditions/', ''),
  ('Santa Monica Playhouse', 'Santa Monica', 'CA', 'https://www.santamonicaplayhouse.com/auditions--submissions.html', ''),
  ('Savannah Repertory Theatre', 'Savannah', 'GA', 'https://savannahrep.org/casting-contact/', ''),
  ('Servant Stage', 'Columbia', 'PA', 'https://www.servantstagecompany.com/auditions', ''),
  ('Shakespeare Festival St. Louis', 'St. Louis', 'MO', NULL, ''),
  ('Sharon Playhouse', 'Sharon', 'CT', NULL, 'On Backstage'),
  ('Shenandoah Summer Music Theatre', 'Winchester', 'VA', 'http://www.ssmtva.org/job/actor/', ''),
  ('Sierra Repertory Theatre', 'Sonora', 'CA', 'https://www.sierrarep.org/work-with-us/', ''),
  ('Signal Ensemble Theatre', 'Chicago', 'IL', 'http://www.theatreinchicago.com/auditions/industrydetail.php?AuditionID=3363', ''),
  ('Signature Theatre', 'Arlington', 'VA', 'http://www.signature-theatre.org/audition-information', ''),
  ('Skylight Music Theatre', 'Milwaukee', 'WI', 'https://www.skylightmusictheatre.org/about/auditions/', ''),
  ('Skyline Theatre Company', 'Fair Lawn', 'NJ', NULL, ''),
  ('Slow Burn Theatre Company', 'Fort Lauderdale', 'FL', NULL, ''),
  ('Smithtown Center for the Performing Arts', 'Smithtown', 'NY', 'http://www.smithtownpac.org/auditions/', ''),
  ('Southern Colorado Repertory Theatre', 'Trinidad', 'CO', NULL, ''),
  ('Southern Plains Productions', 'Oklahoma City', 'OK', NULL, ''),
  ('Speakeasy Stage Company', 'Boston', 'MA', 'https://speakeasystage.com/about/work-with-us/', 'Equity but non-eq can apply'),
  ('Springer Opera House', 'Columbus', 'GA', NULL, ''),
  ('St Jean''s Players', 'New York', 'NY', 'http://www.stjeansplayers.org/', 'no pay'),
  ('Stage One Theatre', 'Louisville', 'KY', NULL, ''),
  ('Stages St. Louis', 'Chesterfield', 'MO', NULL, ''),
  ('Stoneham Theatre', 'Stoneham', 'MA', 'https://www.greaterbostonstage.org/about-us/auditions/', ''),
  ('Studio Tenn', 'Franklin', 'TN', NULL, ''),
  ('Studio Theatre', 'Washington', 'DC', NULL, ''),
  ('Studio Theatre Tierra De Sol', 'The Villages', 'FL', 'https://www.thesharonstudio.com/auditions.html', ''),
  ('Summer Lyric Theatre at Tulane University', 'New Orleans', 'LA', 'https://liberalarts.tulane.edu/summer-lyric-theatre/auditions', ''),
  ('Summer Stock Austin', 'Austin', 'TX', NULL, ''),
  ('Summer Theatre of New Canaan', 'Canaan', 'CT', 'https://www.stonc.org/education-programs/college-internship-program', ''),
  ('Suncoast Broadway Dinner Theatre', 'Hudson', 'FL', 'https://www.suncoastbroadway.com/casting', ''),
  ('Sundance Summer Theatre', 'Sundance', 'UT', 'https://www.sundanceresort.com/summer-theatre/', ''),
  ('Tent Theatre', 'Springfield', 'MO', NULL, ''),
  ('TexArts', 'Austin', 'TX', 'https://www.tex-arts.org/about/professional-auditions/', ''),
  ('Texas Shakespeare Festival', 'Kilgore', 'TX', 'http://www.texasshakespeare.com/actors', ''),
  ('The Barn Dinner Theatre', 'Greensboro', 'NC', 'https://www.barndinner.com/auditions', ''),
  ('The Barnstormers Theatre', 'Tamworth', 'NH', 'http://www.barnstormerstheater.com/auditions.html', 'On Backstage'),
  ('The Black Hills Playhouse', 'Custer', 'SD', 'https://www.blackhillsplayhouse.com/seasonal-employment', ''),
  ('The Candlelight Theatre', 'Wilmington', 'DE', 'https://candlelighttheatredelaware.org/auditions/?_gl=1*2xcy3x*_ga*MTM0ODM4MDUzNC4xNjc1NzI1ODY3*_ga_B1B6Y6N0PJ*MTY3NTcyNTg2Ni4xLjAuMTY3NTcyNTg2Ni4wLjAuMA..&_ga=2.106488842.806872598.1675725868-1348380534.1675725867', ''),
  ('The Eagle Theatre', 'Hammonton', 'NJ', NULL, ''),
  ('The Firehouse Theatre', 'Farmers Branch', 'TX', NULL, ''),
  ('The Gateway', 'Bellport', 'NY', 'https://thegateway.org/Online/default.asp?BOparam::WScontent::loadArticle::permalink=casting&BOparam::WScontent::loadArticle::context_id=&menu_id=5758BEBC-DF40-4AF2-95EC-B887F70C8A34', ''),
  ('The Geva Theatre', 'Rochester', 'NY', 'https://www.gevatheatre.org/artists/casting/', ''),
  ('The Glimmerglass Festival', 'Cooperstown', 'NY', 'https://glimmerglass.org/auditions/', ''),
  ('The Henegar Center', 'Melbourne', 'FL', 'https://henegarcenter.com/auditions/', 'only a  travel stipend'),
  ('The Legacy Theatre', 'Tyrone', 'GA', 'http://www.thelegacytheatre.org/info/auditions.php', ''),
  ('The Lexington Theatre Company', 'Lexington', 'KY', NULL, ''),
  ('The Little  Victory Theatre', 'Staten Island', 'NY', 'http://www.littlevictorytheatre.com/auditions.html', ''),
  ('The Lyric Stage Company of Boston', 'Boston', 'MA', 'https://www.lyricstage.com/about/get-involved/auditions/', ''),
  ('The Market Theatre', 'Audition — Market Theatre | Anderson', 'SC', NULL, ''),
  ('The Moonlight', 'Vista', 'CA', NULL, ''),
  ('The Muny', 'St. Louis', 'MO', 'https://muny.org/jobs/', ''),
  ('The New Paradigm Theatre Company', 'Stamford', 'CT', NULL, ''),
  ('The North Street Playhouse', 'Onancock', 'VA', 'http://northstreetplayhouse.org/auditions', ''),
  ('The Palace Theatre', 'Manchester', 'NH', 'https://palacetheatre.org/jobs/actors/', ''),
  ('The Paul Bunyan Playhouse', 'Bemidji', 'MN', 'http://www.thechieftheater.com/audition-information.html', ''),
  ('The Playmill Theatre', 'West Yellowstone', 'MT', 'https://www.playmill.com/', ''),
  ('The Prizery Theatre', 'South Boston', 'VA', NULL, ''),
  ('The Public Theatre of San Antonio', 'San Antonio', 'TX', 'https://thepublicsa.org/services/auditions/', ''),
  ('The Redhouse', 'Syracuse', 'NY', 'http://www.theredhouse.org/auditions/', ''),
  ('The REV Theatre Company', 'Auburn', 'NY', NULL, ''),
  ('The Stephen Foster Story', 'Bradstown', 'KY', 'http://www.stephenfoster.com/auditions/', ''),
  ('The Temple Theatre Company', 'Sanford', 'NC', NULL, ''),
  ('The Theatre Lab', 'Dayton', 'OH', 'https://www.theatrelabdayton.org/auditions', ''),
  ('The Thousand Island Playhouse', 'Gananoque', 'ON', 'http://www.1000islandsplayhouse.com/auditions/', 'Acting Only'),
  ('The Umbrella Arts Center', 'Concord', 'MA', 'https://theumbrellaarts.org/performing-arts/theater/auditions-opportunities', ''),
  ('The Winter Park Playhouse', 'Winter Park', 'FL', 'https://www.winterparkplayhouse.org/GetInvolved.html', ''),
  ('Theatre Aspen', 'Aspen', 'CO', NULL, ''),
  ('Theatre at the Center', 'Muster', 'IN', 'https://www.theatreatthecenter.com/mission-statement/casting', ''),
  ('Theatre Raleigh', 'Raleigh', 'NC', 'http://www.theatreraleigh.com/about-us/auditions/', ''),
  ('Theatre SilCo', 'Silverthorne', 'CO', 'http://www.lakedillontheatre.org/join-the-team/auditions/', ''),
  ('Theatre Under the Stars', 'Houston', 'TX', 'https://www.tuts.com/about/auditions', ''),
  ('Theatre West', 'Scottsbluff', 'NE', NULL, ''),
  ('Theatre West End', 'Sanford', 'FL', 'https://theaterwestend.com/auditions', ''),
  ('Theatre West Virginia', 'Beaver', 'WV', 'https://www.theatrewestvirginia.org/auditions/', ''),
  ('Theatre Winter Haven', 'Winter Haven', 'FL', NULL, ''),
  ('Theatre Workshop of Nantucket', 'Nantucket', 'MA', 'https://theatrenantucket.org/about/auditions', ''),
  ('Thin Air Theatre Company', 'Cripple Creek', 'CO', NULL, ''),
  ('Thunder Bay Theatre', 'Alpena', 'MI', NULL, ''),
  ('Tibbets Theatre', 'Get Involved | Tibbits Opera House | Coldwater', 'MichiganTibbits', NULL, ''),
  ('Timber Lake Playhouse', 'Mt Carroll', 'IL', NULL, ''),
  ('Tipping Point Theatre', 'Northville', 'MI', NULL, ''),
  ('Titusville Playhouse', 'Titusville', 'FL', NULL, ''),
  ('Toby''s Dinner Theatre', 'Columbia', 'MD', 'https://tobysdinnertheatre.com/about-us/auditions-employment/', ''),
  ('Totem Pole Playhouse', 'Fayetteville', 'PA', 'https://totempoleplayhouse.org/about-the-theatre/auditions/', ''),
  ('Uptown Players', 'Dallas', 'TX', NULL, ''),
  ('Utah Festival', 'Logan', 'UT', 'http://www.utahfestival.org/index.php?p_resource=about_auditions', ''),
  ('Utah Shakespeare Festival', 'Cedar City', 'UT', 'https://www.bard.org/about/employment/', ''),
  ('Vero Beach Theatre Guild', 'Vero Beach', 'FL', NULL, ''),
  ('Village Theatre', 'Auditions - Village Theatre in Issaquah & Everett', 'WA', NULL, ''),
  ('Vintage Theatre', 'Aurora', 'CO', 'https://www.vintagetheatre.com/auditions/', ''),
  ('Virginia Music Theatre', 'Virginia Beach', 'VA', 'http://www.vmtheatre.org/index.php/auditions', ''),
  ('Virginia Rep Theatre', 'Richmond', 'VA', 'http://va-rep.org/auditions.html', ''),
  ('Virginia Stage Company', 'Norfolk', 'VA', 'https://www.vastage.org/auditions/', ''),
  ('Wagon Wheel Theatre', 'Warsaw', 'IN', NULL, ''),
  ('Warsaw Federal Incline Theater', 'Cincinnati', 'OH', 'http://www.cincinnatilandmarkproductions.com/Incline/Auditions.aspx', 'No Housing'),
  ('Waterfront Playhouse', 'Key West', 'FL', 'https://www.waterfrontplayhouse.org/auditions/auditions/', ''),
  ('Weathervane Playhouse', 'Newark', 'OH', 'http://www.weathervaneplayhouse.org/index.php/getinvolved/audition', ''),
  ('West Virginia Public Theatre', 'Morgantown', 'WV', NULL, ''),
  ('Wheelock Family Dinner', 'Boston', 'MA', 'https://www.wheelockfamilytheatre.org/auditions/', ''),
  ('Wick Theatre', 'Boca Raton', 'FL', NULL, ''),
  ('Williamstown  Theatre Festival', 'Williamstown', 'MA', 'https://wtfestival.org/work-learn/', ''),
  ('Winnipesaukee Playhouse', 'Meredith', 'NH', 'http://www.winnipesaukeeplayhouse.org/professional-company-employment.html', ''),
  ('Wolfbane Productions', 'Appomattox', 'VA', 'https://www.wolfbane.org/auditions/', ''),
  ('Woodminster Summer Musicals', 'Oakland', 'CA', NULL, ''),
  ('Woodstock Playhouse', 'Woodstock', 'NY', 'http://www.woodstockplayhouse.org/employment--casting', ''),
  ('Yorktown Stage', 'Yorktown Heights', 'NY', 'https://www.yorktownstage.org/auditions-for-yorktown-stage/', ''),
  ('Zach Theatre', 'Austin', 'TX', NULL, '')
;