// Auto-generated from Non-Equity Theatre List 5.0 — do not edit by hand.
// Entries with url=null had text-only hyperlinks in the source doc; add URLs manually.

export interface TheaterSeed {
  name: string;
  city: string;
  state: string;
  audition_page_url: string | null;
  notes: string;
}

export const theaterSeeds: TheaterSeed[] = [
  {
    name: "3-D Theatrics",
    city: "Long Beach",
    state: "CA",
    audition_page_url: "https://www.3dtheatricals.org/auditions/",
    notes: "No housing or transportation provided",
  },
  {
    name: "5th Ave Theatre",
    city: "Seattle",
    state: "WA",
    audition_page_url: "https://www.5thavenue.org/about/careers/auditions/",
    notes: "",
  },
  {
    name: "7 Angels Theatre",
    city: "Waterbury",
    state: "CT",
    audition_page_url: "https://www.7atheatre.org/work-with-us",
    notes: "",
  },
  {
    name: "Act 2 Playhouse",
    city: "Ambler",
    state: "PA",
    audition_page_url: "https://act2.org/about/casting/",
    notes: "",
  },
  {
    name: "Actors Theatre of Indiana",
    city: "Carmel",
    state: "IN",
    audition_page_url: "http://atistage.org/auditions/",
    notes: "",
  },
  {
    name: "Actors’ Playhouse at the Miracle Theatre",
    city: "Coral Gables",
    state: "FL",
    audition_page_url: "https://www.actorsplayhouse.org/auditions/",
    notes: "",
  },
  {
    name: "Actors’ Repertory Theatre of Simi",
    city: "Simi Valley",
    state: "CA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "AD Players",
    city: "Houston",
    state: "TX",
    audition_page_url: "https://www.adplayers.org/audition",
    notes: "",
  },
  {
    name: "Alabama Shakespeare Festival",
    city: "Montgomery",
    state: "AL",
    audition_page_url: "https://asf.net/auditions/",
    notes: "",
  },
  {
    name: "Algonquin Arts Center",
    city: "Manasquan",
    state: "NJ",
    audition_page_url: "http://www.algonquinarts.com/auditions.php",
    notes: "",
  },
  {
    name: "Alhambra Theatre and Dining",
    city: "Jacksonville",
    state: "FL",
    audition_page_url: null,
    notes: "Equity-but can send in stuff",
  },
  {
    name: "Alluvion Stage Company",
    city: "Lynchburg",
    state: "VA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Alpine Theatre Project",
    city: "Whitefish",
    state: "MT",
    audition_page_url: "https://atpwhitefish.org/jobs-auditions",
    notes: "internships by invitation only",
  },
  {
    name: "Altarena Playhouse",
    city: "Alameda",
    state: "CA",
    audition_page_url: "https://www.altarena.org/2020-auditions",
    notes: "",
  },
  {
    name: "Amarillo Opera",
    city: "Amarillo",
    state: "TX",
    audition_page_url: "https://www.amarilloopera.org/",
    notes: "",
  },
  {
    name: "American Stage Theatre",
    city: "St. Petersburg",
    state: "FL",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Annapolis Opera",
    city: "Annapolis",
    state: "MD",
    audition_page_url: "http://annapolisopera.org/auditions/",
    notes: "",
  },
  {
    name: "Arena Stage DC",
    city: "Washington",
    state: "DC",
    audition_page_url: "https://www.arenastage.org/opportunities/",
    notes: "",
  },
  {
    name: "Arizona Broadway Theatre",
    city: "Peoria",
    state: "AZ",
    audition_page_url: "https://azbroadway.org/about-us/employment-auditions-internships/",
    notes: "",
  },
  {
    name: "Arizona Theatre Company",
    city: "Tucson",
    state: "AZ",
    audition_page_url: "https://arizonatheatre.org/auditions-submissions/",
    notes: "",
  },
  {
    name: "Arkansas Rep",
    city: "Little Rock",
    state: "AR",
    audition_page_url: "https://www.therep.org/work-with-us/",
    notes: "",
  },
  {
    name: "Arrow Rock Lyceum Theatre",
    city: "Arrow Rock",
    state: "MO",
    audition_page_url: "http://lyceumtheatre.org/about/auditions/",
    notes: "",
  },
  {
    name: "ArtisTree Music Theatre Festival- The Grange Theatre",
    city: "Promfret",
    state: "VT",
    audition_page_url: "https://artistreevt.org/auditions/",
    notes: "",
  },
  {
    name: "Arvada Center for the Arts",
    city: "Arvada",
    state: "CO",
    audition_page_url: "https://arvadacenter.org/theatre/auditions",
    notes: "",
  },
  {
    name: "Athens Theatre",
    city: "Deland",
    state: "FL",
    audition_page_url: "https://athensdeland.com/auditions/",
    notes: "",
  },
  {
    name: "Barn Theatre School",
    city: "Augusta",
    state: "MI",
    audition_page_url: "https://barntheatreschool.org/professional-theatre-auditions-apprenticeship/",
    notes: "EMC program",
  },
  {
    name: "Barter Theatre",
    city: "Abingdon",
    state: "VA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "BDT Stage",
    city: "Boulder",
    state: "CO",
    audition_page_url: "https://bdtstage.com/backstage/auditions-jobs/",
    notes: "",
  },
  {
    name: "Beck Center for the Arts",
    city: "Lakewood",
    state: "OH",
    audition_page_url: "http://www.beckcenter.org/what-we-do/theater/auditions/",
    notes: "",
  },
  {
    name: "Beef & Boards Dinner Theatre",
    city: "Indianapolis",
    state: "IN",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Berkeley Playhouse",
    city: "Berkeley",
    state: "CA",
    audition_page_url: "https://tickets.berkeleyplayhouse.org/online/default.asp?doWork::WScontent::loadArticle=Load&BOparam::WScontent::loadArticle::article_id=E4A4CA22-72D6-41CE-97EE-3014A7FEF17F&menu_id=3CD3099C-E1FA-45ED-8066-9C7856768BBA",
    notes: "",
  },
  {
    name: "Berkshire Theatre Group",
    city: "Pittsfield",
    state: "MA",
    audition_page_url: "https://www.berkshiretheatregroup.org/shrek-the-musical-audition-call/",
    notes: "Acting Internship",
  },
  {
    name: "Big Arts Sanibel Island",
    city: "Sanibel Island",
    state: "FL",
    audition_page_url: null,
    notes: "BIG ARTS",
  },
  {
    name: "Big Nosie Theatre",
    city: "Des Plaines",
    state: "IL",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "BigFork Summer Theatre",
    city: "Bigfork",
    state: "MT",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Bluff City Theatre",
    city: "Hannibal",
    state: "MO",
    audition_page_url: "http://bluffcitytheater.com/auditions-at-bluff-city-theater-this-weekend-dont-miss-your-chance/",
    notes: "",
  },
  {
    name: "Bristol Riverside Theatre",
    city: "Bristol",
    state: "PA",
    audition_page_url: "https://www.brtstage.org/employment-opportunities/",
    notes: "",
  },
  {
    name: "Broadway Palm Dinner Theatre",
    city: "Fort Myers",
    state: "FL",
    audition_page_url: "http://broadwaypalm.com/backstage/auditions/",
    notes: "",
  },
  {
    name: "Broadway Rose Theatre Company",
    city: "Tigard",
    state: "OR",
    audition_page_url: "https://www.broadwayrose.org/auditions",
    notes: "",
  },
  {
    name: "Broadway Theatre of Pitman",
    city: "Pitman",
    state: "NJ",
    audition_page_url: "https://www.thebroadwaytheatre.org/auditions/",
    notes: "Housing?",
  },
  {
    name: "Cabrillo Music Theatre",
    city: "Thousand Oaks",
    state: "CA",
    audition_page_url: "https://www.cabrillostage.com/auditions",
    notes: "No housing",
  },
  {
    name: "Cain Park",
    city: "Cleveland Heights",
    state: "OH",
    audition_page_url: "https://www.cainpark.com/241/Performance",
    notes: "",
  },
  {
    name: "Cape Fear Regional Theatre",
    city: "Fayetteville",
    state: "NC",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Capitol Repertory Theatre",
    city: "Albany",
    state: "NY",
    audition_page_url: "https://capitalrep.org/auditions/",
    notes: "",
  },
  {
    name: "Cardinal Stage Company",
    city: "Bloomington",
    state: "IN",
    audition_page_url: "https://cardinalstage.org/about-us/auditions/",
    notes: "",
  },
  {
    name: "Carousel Music Theatre",
    city: "Boothbay Harbor",
    state: "ME",
    audition_page_url: "https://www.carouselmusictheater.org/auditions.html",
    notes: "",
  },
  {
    name: "Casa Manana Theatre",
    city: "Fort Worth",
    state: "TX",
    audition_page_url: "http://www.casamanana.org/about/auditions/",
    notes: "",
  },
  {
    name: "Cedar Summerstock Theater",
    city: "Ansgar",
    state: "IA",
    audition_page_url: "https://www.cedarsummerstock.org/auditions",
    notes: "",
  },
  {
    name: "Cedar Summerstock Theatre",
    city: "Ansgar",
    state: "IA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Chanhassen Dinner Theatre",
    city: "Chanhassen",
    state: "MN",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Charleston Stage",
    city: "Charleston",
    state: "NC",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Charlottsville Opera",
    city: "Charlottesville",
    state: "VA",
    audition_page_url: "https://www.charlottesvilleopera.org/chorus.html",
    notes: "",
  },
  {
    name: "Chenango River Theatre",
    city: "Greene",
    state: "NY",
    audition_page_url: "http://www.chenangorivertheatre.org/Chenango_River_Theatre/Auditions_Jobs.html",
    notes: "Acting only",
  },
  {
    name: "Cincinnati Playhouse in the Park",
    city: "Cincinnati",
    state: "OH",
    audition_page_url: "https://www.cincyplay.com/employment",
    notes: "",
  },
  {
    name: "Circa21 Dinner Playhouse",
    city: "Rock Island",
    state: "IL",
    audition_page_url: "http://www.circa21.com/auditions",
    notes: "",
  },
  {
    name: "City Springs Theatre Company",
    city: "Sandy Springs",
    state: "GA",
    audition_page_url: "https://www.cityspringstheatre.com/auditions/",
    notes: "",
  },
  {
    name: "Clinton Area Showboat Theatre",
    city: "Clinton",
    state: "IA",
    audition_page_url: "https://www.clintonshowboat.com/audition-information",
    notes: "",
  },
  {
    name: "Coeur d’ Alene Summer Theatre",
    city: "Coeur’d Alene",
    state: "ID",
    audition_page_url: "http://www.cdasummertheatre.com/auditions.html",
    notes: "",
  },
  {
    name: "Colorado Theatre Guild",
    city: "",
    state: "CO",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Conwell’s Dinner Theatre",
    city: "Marshall",
    state: "MI",
    audition_page_url: "https://www.turkeyville.com/dinner-theatre/casting-and-employment/",
    notes: "",
  },
  {
    name: "Cortland Rep Theatre",
    city: "Cortland",
    state: "NY",
    audition_page_url: "https://www.cortlandrep.org/employment/",
    notes: "",
  },
  {
    name: "Covedale Center for the Performing Arts",
    city: "Cincinnati",
    state: "OH",
    audition_page_url: "http://www.cincinnatilandmarkproductions.com/ccpa/Auditions.aspx",
    notes: "",
  },
  {
    name: "CPCC Summer Theatre Auditions",
    city: "Charlotte",
    state: "NC",
    audition_page_url: "http://blogs.cpcc.edu/theatre/auditions/cpcc-summer-theatre-auditions/",
    notes: "",
  },
  {
    name: "Crane River Theatre",
    city: "Kearney",
    state: "NE",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Creede Rep Theatre",
    city: "Creede",
    state: "CO",
    audition_page_url: "https://creederep.org/work-with-us/job-opportunities/",
    notes: "",
  },
  {
    name: "Cumberland County Playhouse",
    city: "Crossville",
    state: "TN",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Cumberland Theatre",
    city: "Cumberland",
    state: "MD",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Cupcake Theatre",
    city: "Los Angles",
    state: "CA",
    audition_page_url: "https://www.facebook.com/pg/CupcakeTheater/events/?ref=page_internal",
    notes: "",
  },
  {
    name: "Cygnet Theatre",
    city: "San Diego",
    state: "CA",
    audition_page_url: "http://www.cygnettheatre.com/about/jobs.php",
    notes: "",
  },
  {
    name: "Dallas Theatre Center",
    city: "Dallas",
    state: "TX",
    audition_page_url: "https://dallastheatercenter.org/auditions/",
    notes: "",
  },
  {
    name: "Denver Center for the Performing Arts",
    city: "Denver",
    state: "CO",
    audition_page_url: "https://www.denvercenter.org/about-us/careers",
    notes: "",
  },
  {
    name: "Derby Dinner Playhouse",
    city: "Clarksville",
    state: "IN",
    audition_page_url: "https://derbydinner.com/auditions/",
    notes: "",
  },
  {
    name: "Downtown Cabaret Theatre",
    city: "Bridgeport",
    state: "CT",
    audition_page_url: "https://dtcab.com/auditions/",
    notes: "",
  },
  {
    name: "Dreamcatcher Rep",
    city: "Summit",
    state: "NJ",
    audition_page_url: "http://www.dreamcatcherrep.org/casting",
    notes: "Equity, but some Non-Equity",
  },
  {
    name: "Drury Lane Theatre",
    city: "Oakbrook Terrace",
    state: "IL",
    audition_page_url: "http://www.drurylaneoakbrook.com/facility/contact-us/auditions",
    notes: "",
  },
  {
    name: "Dutch Apple Dinner Theatre",
    city: "Lancaster",
    state: "PA",
    audition_page_url: "https://dutchapple.com/backstage/auditions/",
    notes: "",
  },
  {
    name: "East Lyme Regional Theatre",
    city: "Niantic",
    state: "CT",
    audition_page_url: "https://www.eastlymeregionaltheater.com/audition-notice",
    notes: "",
  },
  {
    name: "Encore Musical Theatre Festival",
    city: "Dexter",
    state: "MI",
    audition_page_url: "https://www.theencoretheatre.org/auditions/",
    notes: "",
  },
  {
    name: "Engeman Theatre",
    city: "Northport",
    state: "NY",
    audition_page_url: "https://www.engemantheater.com/auditions",
    notes: "",
  },
  {
    name: "Ensemble Stage",
    city: "Banner Elk",
    state: "NC",
    audition_page_url: "http://www.ensemblestage.com/auditions.html",
    notes: "Acting Only",
  },
  {
    name: "Ensemble Theatre of Cincinnati",
    city: "Cincinnati",
    state: "OH",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Exit 86 Theatre",
    city: "Elmira",
    state: "NY",
    audition_page_url: "https://www.exit82theatre.com/",
    notes: "",
  },
  {
    name: "Farmers Alley Theatre",
    city: "Kalamazoo",
    state: "MI",
    audition_page_url: "http://www.farmersalleytheatre.com/auditions",
    notes: "",
  },
  {
    name: "Festival  56",
    city: "Princeton",
    state: "IL",
    audition_page_url: "http://www.festival56.com/employment",
    notes: "",
  },
  {
    name: "Finger Lakes Musical Theatre Festival",
    city: "Auburn",
    state: "NY",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Firehouse Center for the Arts",
    city: "Newburyport",
    state: "MA",
    audition_page_url: "https://www.firehouse.org/auditions/",
    notes: "",
  },
  {
    name: "Fireside Theatre",
    city: "Fort Atkinson",
    state: "WI",
    audition_page_url: "http://www.firesidetheatre.com/",
    notes: "On Backstage",
  },
  {
    name: "Flat Rock Playhouse",
    city: "Flat Rock",
    state: "NC",
    audition_page_url: "https://www.flatrockplayhouse.org/youth-auditions",
    notes: "",
  },
  {
    name: "Florida Repertory Theatre",
    city: "Fort Myers",
    state: "FL",
    audition_page_url: "https://www.floridarep.org/about-florida-rep/casting-calls/",
    notes: "",
  },
  {
    name: "Florida Studio Theatre",
    city: "Sarasota",
    state: "FL",
    audition_page_url: "https://www.floridastudiotheatre.org/casting-and-hiring",
    notes: "Equity with non-equity internships",
  },
  {
    name: "Fort Peck Summer Theatre",
    city: "Fort Peck",
    state: "MT",
    audition_page_url: "https://www.fortpecktheatre.org/auditions",
    notes: "",
  },
  {
    name: "Four Corners Musical Theatre",
    city: "Farmington",
    state: "NM",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Four Seasons Theatre",
    city: "Madison",
    state: "WI",
    audition_page_url: "http://fourseasonstheatre.com/auditions/",
    notes: "",
  },
  {
    name: "Fulton Theatre",
    city: "Lancaster",
    state: "PA",
    audition_page_url: "http://www.thefulton.org/about/auditions/",
    notes: "",
  },
  {
    name: "Garden Theatre",
    city: "Winter Garden",
    state: "FL",
    audition_page_url: "http://www.gardentheatre.org/get-involved/audition/",
    notes: "no housing",
  },
  {
    name: "Garland Summer Musicals",
    city: "Garland",
    state: "TX",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Garland Theatre",
    city: "Garland",
    state: "TX",
    audition_page_url: "https://www.garlandsummermusicals.org/index.php/season-schedule/auditions",
    notes: "",
  },
  {
    name: "Gateway Playhouse",
    city: "Somers Point",
    state: "NJ",
    audition_page_url: "http://www.gatewaybythebay.org/",
    notes: "",
  },
  {
    name: "Glow Lyric Theatre",
    city: "Greenville",
    state: "SC",
    audition_page_url: "http://glowlyric.com/about-us-2/auditions/",
    notes: "",
  },
  {
    name: "Goodman Theatre",
    city: "Chicago",
    state: "IL",
    audition_page_url: "http://www.goodmantheatre.org/About/Auditions/",
    notes: "Acting Only",
  },
  {
    name: "Granbury Theatre Company",
    city: "Granbury",
    state: "TX",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Great Lakes Theatre",
    city: "Cleveland",
    state: "OH",
    audition_page_url: "http://www.greatlakestheater.org/work-with-us/auditions",
    notes: "",
  },
  {
    name: "Great Plains Theatre",
    city: "Abilene",
    state: "KS",
    audition_page_url: "http://www.greatplainstheatre.com/auditions",
    notes: "",
  },
  {
    name: "Greater Ocean City Company",
    city: "Ocean City",
    state: "NJ",
    audition_page_url: "http://oceancitytheatrecompany.com/about/casting/",
    notes: "",
  },
  {
    name: "Greenbrier Valley Theatre",
    city: "Lewisburg",
    state: "WV",
    audition_page_url: "https://www.gvtheatre.org/educationauditions",
    notes: "",
  },
  {
    name: "Greenville Theatre",
    city: "Greenville",
    state: "SC",
    audition_page_url: null,
    notes: "local actors only",
  },
  {
    name: "Gretna Theatre",
    city: "Mount Gretna",
    state: "PA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Gulfshore Playhouse",
    city: "Naples",
    state: "FL",
    audition_page_url: "https://www.gulfshoreplayhouse.org/summer-2017-auditions/",
    notes: "Plays Only",
  },
  {
    name: "Hale Center Theatre Orem",
    city: "Orem",
    state: "UT",
    audition_page_url: "http://www.haletheater.org/theater/auditions/",
    notes: "",
  },
  {
    name: "Hale Centre Theatre",
    city: "Sandy",
    state: "UT",
    audition_page_url: "https://www.haletheatrearizona.com/Online/default.asp?BOparam::WScontent::loadArticle::permalink=auditions&BOparam::WScontent::loadArticle::context_id=",
    notes: "",
  },
  {
    name: "Hanger Theatre",
    city: "Ithaca",
    state: "NY",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Hanover Theatre",
    city: "Worcester",
    state: "MA",
    audition_page_url: "https://thehanovertheatre.org/auditions.php",
    notes: "",
  },
  {
    name: "Harbor Stage Company",
    city: "Wellfleet",
    state: "MA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Heritage Theatre",
    city: "Perry",
    state: "UT",
    audition_page_url: "https://www.heritagetheatreutah.com/auditions",
    notes: "",
  },
  {
    name: "Highland Summer Theatre",
    city: "Mankato",
    state: "MN",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Hillbarn Theatre",
    city: "Foster City",
    state: "CA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Hippodrome Theatre",
    city: "Gainesville",
    state: "FL",
    audition_page_url: "https://thehipp.org/auditions/",
    notes: "Equity but non-eq can apply",
  },
  {
    name: "Hope Rep Theatre",
    city: "Holland",
    state: "MI",
    audition_page_url: "https://www.facebook.com/hopesummertheatre/",
    notes: "On Facebook, Broadway World",
  },
  {
    name: "Hunterdon Hills Playhouse",
    city: "Hampton",
    state: "NJ",
    audition_page_url: "http://www.hhplayhouse.com/index.php?src=gendocs&ref=Contact",
    notes: "On Backstage",
  },
  {
    name: "Huntington Theatre Company",
    city: "Boston",
    state: "MA",
    audition_page_url: "https://www.huntingtontheatre.org/auditions/",
    notes: "",
  },
  {
    name: "Idaho Shakespeare Festival",
    city: "Boise",
    state: "ID",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Inland Valley Repertory Theatre",
    city: "Claremont",
    state: "CA",
    audition_page_url: "https://www.ivrt.org/audition",
    notes: "",
  },
  {
    name: "Interlakes Summer Theatre",
    city: "Meredith",
    state: "NH",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Iron Bridge Theatre",
    city: "Tyrone",
    state: "PA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Ivoryton Playhouse",
    city: "Ivoryton",
    state: "CT",
    audition_page_url: "http://www.ivorytonplayhouse.org/get-involved",
    notes: "",
  },
  {
    name: "Jean’s Playhouse",
    city: "Lincoln",
    state: "NH",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Jefferson Performing Arts Society",
    city: "Metairie",
    state: "LA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Jewel Theatre Company",
    city: "Santa Cruz",
    state: "CA",
    audition_page_url: "https://www.jeweltheatre.net/auditions/",
    notes: "",
  },
  {
    name: "Judson Theatre Company",
    city: "Southern Pines",
    state: "North Carolina",
    audition_page_url: "https://judsontheatre.com/contact-us/",
    notes: "",
  },
  {
    name: "Kalamazoo Civic Theatre",
    city: "Kalamazoo",
    state: "MI",
    audition_page_url: "https://www.kazoocivic.com/auditions",
    notes: "",
  },
  {
    name: "Kansas City Rep Theatre",
    city: "Kansas City",
    state: "MO",
    audition_page_url: "https://opportunities.kcrep.org/auditions/",
    notes: "",
  },
  {
    name: "Kansas City Starlight Theatre",
    city: "Kansas City",
    state: "MO",
    audition_page_url: "http://www.kcstarlight.com/broadway/auditions.aspx",
    notes: "Equity",
  },
  {
    name: "Keegan Theatre",
    city: "Washington",
    state: "DC",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Kincaid Regional Theatre",
    city: "Falmouth",
    state: "KY",
    audition_page_url: "https://www.krtshows.com/auditions",
    notes: "",
  },
  {
    name: "La Comedia Dinner Theatre",
    city: "Springboro",
    state: "OH",
    audition_page_url: "https://lacomedia.com/audition-info/",
    notes: "",
  },
  {
    name: "Lake City Playhouse",
    city: "Coeur’d Alene",
    state: "ID",
    audition_page_url: "http://www.lakecityplayhouse.org/auditions",
    notes: "",
  },
  {
    name: "Lakewood Center for the Arts",
    city: "Lake Oswego",
    state: "OR",
    audition_page_url: "https://lakewood-center.org/theatre/auditions/",
    notes: "",
  },
  {
    name: "Leavenworth Summer Theatre",
    city: "",
    state: "",
    audition_page_url: "https://leavenworthsummertheater.org/auditions",
    notes: "",
  },
  {
    name: "Lees-McRae Summer Theatre",
    city: "Banner Elk",
    state: "NC",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Legendary Theatre",
    city: "Redlands",
    state: "CA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Little Theatre on the Square",
    city: "Sullivan",
    state: "IL",
    audition_page_url: "http://www.thelittletheatre.org/contact-us/auditions/",
    notes: "",
  },
  {
    name: "Lost Nation Theatre",
    city: "Montpelier",
    state: "VT",
    audition_page_url: "https://lostnationtheater.org/auditions-and-employment.html",
    notes: "",
  },
  {
    name: "Lyric Stage of Boston",
    city: "Boston",
    state: "MA",
    audition_page_url: null,
    notes: "no housing",
  },
  {
    name: "Lyric Theatre of Oklahoma",
    city: "Oklahoma City",
    state: "OK",
    audition_page_url: "http://www.lyrictheatreokc.com/about-the-lyric/auditions",
    notes: "",
  },
  {
    name: "Mac-Haydn Theatre",
    city: "Chatham",
    state: "NY",
    audition_page_url: "http://www.machaydntheatre.org/",
    notes: "",
  },
  {
    name: "Maine State Music Theatre",
    city: "Brunswick",
    state: "ME",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Maltz Jupiter Theatre",
    city: "Jupiter",
    state: "FL",
    audition_page_url: "https://www.jupitertheatre.org/2223-auditions",
    notes: "",
  },
  {
    name: "Maples Repertory Theatre",
    city: "Macon",
    state: "MO",
    audition_page_url: "http://maplesrep.com/about/work-with-us/",
    notes: "",
  },
  {
    name: "Marriott Theatre",
    city: "Lincolnshire",
    state: "IL",
    audition_page_url: "http://www.marriotttheatre.com/employment-and-auditions",
    notes: "",
  },
  {
    name: "Mason Street Warehouse",
    city: "Saugatuck",
    state: "MI",
    audition_page_url: "https://sc4a.org/msw/",
    notes: "",
  },
  {
    name: "McCoy Rigby Entertainment",
    city: "Yorba Linda",
    state: "CA",
    audition_page_url: "https://www.florescasting.com/auditions",
    notes: "",
  },
  {
    name: "Mcleod Summer Playhouse",
    city: "Carbondale",
    state: "IL",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Media Theatre",
    city: "Media",
    state: "PA",
    audition_page_url: "https://mediatheatre.org/special-events/calendar/jan6and7auditions/",
    notes: "",
  },
  {
    name: "Medow Brook Theatre",
    city: "Rochester Hills",
    state: "MI",
    audition_page_url: "http://www.mbtheatre.com/auditions/",
    notes: "",
  },
  {
    name: "Mill Mountain Playhouse",
    city: "Roanoke",
    state: "VA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Millbrook Playhouse",
    city: "Mill Hall",
    state: "PA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Milton Theatre",
    city: "Milton",
    state: "DE",
    audition_page_url: "https://www.miltontheatre.com/auditions",
    notes: "",
  },
  {
    name: "Milwaukee Rep Theatre",
    city: "Milwaukee",
    state: "WI",
    audition_page_url: "https://www.milwaukeerep.com/about/work-us/professional-residencies/",
    notes: "Acting Internship, plays only",
  },
  {
    name: "Miners Alley Playhouse",
    city: "Golden",
    state: "Colorado",
    audition_page_url: "https://minersalley.com/about/auditions/",
    notes: "",
  },
  {
    name: "Montgomery Theatre",
    city: "Souderton",
    state: "PA",
    audition_page_url: "https://www.montgomerytheater.org/opportunities",
    notes: "no housing",
  },
  {
    name: "Mountain Play",
    city: "Mill Valley",
    state: "CA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Mountain Theatre Company",
    city: "Highlands",
    state: "NC",
    audition_page_url: "https://www.mountaintheatre.com/auditions",
    notes: "",
  },
  {
    name: "MTH Theatre at Crown Center",
    city: "Kansas City",
    state: "MO",
    audition_page_url: "https://musicaltheaterheritage.com/auditions/",
    notes: "",
  },
  {
    name: "Music Theatre of Wichita",
    city: "Wichita",
    state: "KS",
    audition_page_url: "https://mtwichita.org/audition/audition-opportunities/",
    notes: "",
  },
  {
    name: "Music Theatre Works",
    city: "Wilmette",
    state: "IL",
    audition_page_url: "https://www.musictheaterworks.com/auditions/",
    notes: "",
  },
  {
    name: "Musical Theatre West",
    city: "Long Beach",
    state: "CA",
    audition_page_url: "http://musical.org/auditions/",
    notes: "",
  },
  {
    name: "Myers Dinner Theatre",
    city: "Hillsboro",
    state: "IN",
    audition_page_url: "https://myersdt.com/theatre-employment",
    notes: "",
  },
  {
    name: "Nashville Rep",
    city: "Nashville",
    state: "TN",
    audition_page_url: "https://nashvillerep.org/audition",
    notes: "",
  },
  {
    name: "Nettle Creek Players",
    city: "Hangerstown",
    state: "IN",
    audition_page_url: "https://www.nettlecreekplayers.com/silnet-auction",
    notes: "",
  },
  {
    name: "New Bedford Theatre Festival",
    city: "New Bedford",
    state: "MA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "New Century Theatre",
    city: "Northampton",
    state: "MA",
    audition_page_url: "http://www.newcenturytheatre.org/audition.html",
    notes: "Plays Only",
  },
  {
    name: "New Hampshire Professional Theatre Association",
    city: "Manchester",
    state: "NH",
    audition_page_url: "https://nhpta.org/auditions/",
    notes: "",
  },
  {
    name: "New London Barn Theatre",
    city: "New London",
    state: "NH",
    audition_page_url: "https://www.nlbarn.org/jobs",
    notes: "",
  },
  {
    name: "New Repertory Theatre",
    city: "Watertown",
    state: "MA",
    audition_page_url: "http://www.newrep.org/",
    notes: "",
  },
  {
    name: "New Stage Theatre",
    city: "Jackson",
    state: "MS",
    audition_page_url: "http://newstagetheatre.com/about/employment/auditions-2/",
    notes: "",
  },
  {
    name: "New Theatre & Restaurant",
    city: "Overland Park",
    state: "KS",
    audition_page_url: "https://newtheatre.com/job-opportunities/",
    notes: "",
  },
  {
    name: "NextStop Theatre Company",
    city: "Herndon",
    state: "VA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "No Name Players",
    city: "Pittsburgh",
    state: "PA",
    audition_page_url: "http://www.nonameplayers.org/",
    notes: "",
  },
  {
    name: "No Square Theatre",
    city: "Laguna Beach",
    state: "CA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "North Carolina Theatre",
    city: "Raleigh",
    state: "NC",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "North Coast Repertory Theatre",
    city: "Solana Beach",
    state: "CA",
    audition_page_url: "https://northcoastrep.org/about-north-coast-repertory-theatre/casting/",
    notes: "",
  },
  {
    name: "North Hampton Community College Summer Theatre",
    city: "Bethlehem",
    state: "PA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "North Shore Music Theatre",
    city: "Beverly",
    state: "MA",
    audition_page_url: "https://www.nsmt.org/auditions.html",
    notes: "",
  },
  {
    name: "Northern Stage",
    city: "White River Junction",
    state: "VT",
    audition_page_url: "https://northernstage.org/employment-auditions/",
    notes: "Equity but non-eq can apply",
  },
  {
    name: "Ogden Musical Theatre",
    city: "Ogden",
    state: "Utah",
    audition_page_url: "https://ogdenmusicaltheatre.org/summerMusical/audition-info",
    notes: "",
  },
  {
    name: "Ogunquit Playhouse",
    city: "Ogunquit",
    state: "ME",
    audition_page_url: "http://www.ogunquitplayhouse.org/auditions/",
    notes: "",
  },
  {
    name: "Olney Theatre Company",
    city: "Olney",
    state: "MD",
    audition_page_url: "https://www.olneytheatre.org/",
    notes: "",
  },
  {
    name: "Opera North",
    city: "Lebanon",
    state: "NH",
    audition_page_url: "https://operanorth.org/",
    notes: "",
  },
  {
    name: "Ordway Theatre",
    city: "St Paul",
    state: "MN",
    audition_page_url: "https://ordway.org/about/employment/auditions/",
    notes: "",
  },
  {
    name: "Oregon Cabaret Theatre",
    city: "Ashland",
    state: "OR",
    audition_page_url: "https://theoregoncabaret.com/backstage/casting/",
    notes: "",
  },
  {
    name: "Orlando Rep Theatre",
    city: "Orlando",
    state: "FL",
    audition_page_url: "https://www.orlandorep.com/get-involved/auditions/",
    notes: "",
  },
  {
    name: "Ozark Actors Theatre",
    city: "Rolla",
    state: "MO",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "P3 Theatre Company",
    city: "Long Beach",
    state: "CA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Pacific Coast Repertory Theatre",
    city: "Pleasanton",
    state: "CA",
    audition_page_url: "http://pcrtproductions.org/casting/",
    notes: "",
  },
  {
    name: "Pagosa Springs Center for the Arts",
    city: "Pagosa Springs",
    state: "CO",
    audition_page_url: "http://pagosacenter.org/auditions-submissions-employment-internships-volunteers/auditions/",
    notes: "",
  },
  {
    name: "Palm Canyon Theatre",
    city: "Palm Springs",
    state: "CA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Parallel 45 Theatre Festival",
    city: "Traverse City",
    state: "MI",
    audition_page_url: "http://www.parallel45.org/opportunities/",
    notes: "",
  },
  {
    name: "Paramount Theatre",
    city: "Aurora",
    state: "IL",
    audition_page_url: "https://paramountaurora.com/opportunities/auditions/",
    notes: "",
  },
  {
    name: "Park Playhouse",
    city: "Albany",
    state: "NY",
    audition_page_url: "http://www.parkplayhouse.com/audition/",
    notes: "",
  },
  {
    name: "Peach State Summer Theatre",
    city: "Valdosta",
    state: "GA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Pennsylvania Shakespeare Festival",
    city: "Allentown",
    state: "PA",
    audition_page_url: "http://www.pashakespeare.org/psf_jobs.php",
    notes: "",
  },
  {
    name: "Pentagle Arts",
    city: "Woodstock",
    state: "VT",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "People’s Light",
    city: "Malvern",
    state: "PA",
    audition_page_url: "https://www.peopleslight.org/about/careers-opportunities/",
    notes: "",
  },
  {
    name: "Peregrine Theatre Ensemble",
    city: "Provincetown",
    state: "Ma",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Peterborough Players",
    city: "Peterborough",
    state: "NH",
    audition_page_url: "https://www.peterboroughplayers.org/auditions.html",
    notes: "",
  },
  {
    name: "Phoenix Theatre",
    city: "Phoenix",
    state: "AZ",
    audition_page_url: "https://www.phoenixtheatre.com/about-us/audition-callback-and-casting-information",
    notes: "",
  },
  {
    name: "Phoenix Theatre",
    city: "Indianapolis",
    state: "IN",
    audition_page_url: "https://www.phoenixtheatre.org/work-with-us",
    notes: "",
  },
  {
    name: "Pickleville Playhouse",
    city: "Garden City",
    state: "UT",
    audition_page_url: "https://www.picklevilleplayhouse.com/auditions",
    notes: "",
  },
  {
    name: "Pines Dinner Theatre",
    city: "Perform at the Pines - Pines Dinner Theatre - Allentown",
    state: "PA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Pittsburgh CLO",
    city: "Pittsburgh",
    state: "PA",
    audition_page_url: "http://www.pittsburghclo.org/pages/clo_auditions",
    notes: "",
  },
  {
    name: "Pittsburgh Musical Theatre",
    city: "Pittsburgh",
    state: "PA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Pittsburgh Playhouse",
    city: "Pittsburgh",
    state: "PA",
    audition_page_url: "http://www.pittsburghplayhouse.com/news/auditions",
    notes: "",
  },
  {
    name: "Playmakers Rep Company",
    city: "Chapel Hill",
    state: "NC",
    audition_page_url: "https://www.playmakersrep.org/about-us/auditions/",
    notes: "Mostly Plays",
  },
  {
    name: "Plaza Theatrics",
    city: "Bellmore",
    state: "NY",
    audition_page_url: "https://plazatheatrical.com/about-us/job-opportunities/",
    notes: "",
  },
  {
    name: "Porchlight Music Theatre",
    city: "Chicago",
    state: "IL",
    audition_page_url: "https://porchlightmusictheatre.org/about/opportunity/",
    notes: "",
  },
  {
    name: "Porthouse Theatre",
    city: "Cuyahoga Falls",
    state: "OH",
    audition_page_url: "https://www.kent.edu/porthouse/auditions",
    notes: "",
  },
  {
    name: "Post Playhouse",
    city: "Harrison",
    state: "NE",
    audition_page_url: "http://postplayhouse.com/industry-professionals/",
    notes: "",
  },
  {
    name: "Prima Theatre",
    city: "Lancaster",
    state: "PA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Queensbury Theatre",
    city: "Houston",
    state: "TX",
    audition_page_url: "https://www.queensburytheatre.org/auditions",
    notes: "",
  },
  {
    name: "Ray of Light Theatre",
    city: "San Francisco",
    state: "CA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Reagle Music Theatre",
    city: "Waltham",
    state: "MA",
    audition_page_url: "https://www.reaglemusictheatre.org/auditions-and-employment",
    notes: "",
  },
  {
    name: "Red Barn Summer Theatre",
    city: "Clinton County",
    state: "IN",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Red Barn Theatre",
    city: "Key West",
    state: "FL",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Red Mountain Theatre Company",
    city: "Brimingham",
    state: "AL",
    audition_page_url: "http://redmountaintheatre.org/auditions/",
    notes: "",
  },
  {
    name: "Regional Theatre of the Palouse",
    city: "Auditions - RTOP Theatre - Pullman",
    state: "WA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Repertory Theatre of St. Louis",
    city: "Webster Groves",
    state: "MO",
    audition_page_url: "http://www.repstl.org/auditions/",
    notes: "Acting Only",
  },
  {
    name: "Riverside Center for the Performing Arts",
    city: "Fredericksburg",
    state: "VA",
    audition_page_url: "https://www.riversidedt.com/auditions/",
    notes: "",
  },
  {
    name: "Rochester Opera House",
    city: "Rochester",
    state: "NY",
    audition_page_url: "http://www.rochesteroperahouse.com/auditions--employment.html",
    notes: "",
  },
  {
    name: "Rocky Mountain Rep Theatre",
    city: "Grand Lake",
    state: "CO",
    audition_page_url: "http://www.rockymountainrep.com/about-rmrt/audition-for-us/",
    notes: "",
  },
  {
    name: "Round Barn Theatre",
    city: "Nappanee",
    state: "IN",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Saint Michael’s Playhouse",
    city: "Colchester",
    state: "VT",
    audition_page_url: "https://saintmichaelsplayhouse.org/get-involved/casting/",
    notes: "Equity but non-eq can apply",
  },
  {
    name: "Salt Lake Acting Company",
    city: "Salt Lake City",
    state: "UT",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "San Antonio Broadway Theatre",
    city: "San Antonio",
    state: "TX",
    audition_page_url: "https://sabroadwaytheatre.com/auditions/",
    notes: "",
  },
  {
    name: "Santa Monica Playhouse",
    city: "Santa Monica",
    state: "CA",
    audition_page_url: "https://www.santamonicaplayhouse.com/auditions--submissions.html",
    notes: "",
  },
  {
    name: "Savannah Repertory Theatre",
    city: "Savannah",
    state: "GA",
    audition_page_url: "https://savannahrep.org/casting-contact/",
    notes: "",
  },
  {
    name: "Servant Stage",
    city: "Columbia",
    state: "PA",
    audition_page_url: "https://www.servantstagecompany.com/auditions",
    notes: "",
  },
  {
    name: "Shakespeare Festival St. Louis",
    city: "St. Louis",
    state: "MO",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Sharon Playhouse",
    city: "Sharon",
    state: "CT",
    audition_page_url: null,
    notes: "On Backstage",
  },
  {
    name: "Shenandoah Summer Music Theatre",
    city: "Winchester",
    state: "VA",
    audition_page_url: "http://www.ssmtva.org/job/actor/",
    notes: "",
  },
  {
    name: "Sierra Repertory Theatre",
    city: "Sonora",
    state: "CA",
    audition_page_url: "https://www.sierrarep.org/work-with-us/",
    notes: "",
  },
  {
    name: "Signal Ensemble Theatre",
    city: "Chicago",
    state: "IL",
    audition_page_url: "http://www.theatreinchicago.com/auditions/industrydetail.php?AuditionID=3363",
    notes: "",
  },
  {
    name: "Signature Theatre",
    city: "Arlington",
    state: "VA",
    audition_page_url: "http://www.signature-theatre.org/audition-information",
    notes: "",
  },
  {
    name: "Skylight Music Theatre",
    city: "Milwaukee",
    state: "WI",
    audition_page_url: "https://www.skylightmusictheatre.org/about/auditions/",
    notes: "",
  },
  {
    name: "Skyline Theatre Company",
    city: "Fair Lawn",
    state: "NJ",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Slow Burn Theatre Company",
    city: "Fort Lauderdale",
    state: "FL",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Smithtown Center for the Performing Arts",
    city: "Smithtown",
    state: "NY",
    audition_page_url: "http://www.smithtownpac.org/auditions/",
    notes: "",
  },
  {
    name: "Southern Colorado Repertory Theatre",
    city: "Trinidad",
    state: "CO",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Southern Plains Productions",
    city: "Oklahoma City",
    state: "OK",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Speakeasy Stage Company",
    city: "Boston",
    state: "MA",
    audition_page_url: "https://speakeasystage.com/about/work-with-us/",
    notes: "Equity but non-eq can apply",
  },
  {
    name: "Springer Opera House",
    city: "Columbus",
    state: "GA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "St Jean’s Players",
    city: "New York",
    state: "NY",
    audition_page_url: "http://www.stjeansplayers.org/",
    notes: "no pay",
  },
  {
    name: "Stage One Theatre",
    city: "Louisville",
    state: "KY",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Stages St. Louis",
    city: "Chesterfield",
    state: "MO",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Stoneham Theatre",
    city: "Stoneham",
    state: "MA",
    audition_page_url: "https://www.greaterbostonstage.org/about-us/auditions/",
    notes: "",
  },
  {
    name: "Studio Tenn",
    city: "Franklin",
    state: "TN",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Studio Theatre",
    city: "Washington",
    state: "DC",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Studio Theatre Tierra De Sol",
    city: "The Villages",
    state: "FL",
    audition_page_url: "https://www.thesharonstudio.com/auditions.html",
    notes: "",
  },
  {
    name: "Summer Lyric Theatre at Tulane University",
    city: "New Orleans",
    state: "LA",
    audition_page_url: "https://liberalarts.tulane.edu/summer-lyric-theatre/auditions",
    notes: "",
  },
  {
    name: "Summer Stock Austin",
    city: "Austin",
    state: "TX",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Summer Theatre of New Canaan",
    city: "Canaan",
    state: "CT",
    audition_page_url: "https://www.stonc.org/education-programs/college-internship-program",
    notes: "",
  },
  {
    name: "Suncoast Broadway Dinner Theatre",
    city: "Hudson",
    state: "FL",
    audition_page_url: "https://www.suncoastbroadway.com/casting",
    notes: "",
  },
  {
    name: "Sundance Summer Theatre",
    city: "Sundance",
    state: "UT",
    audition_page_url: "https://www.sundanceresort.com/summer-theatre/",
    notes: "",
  },
  {
    name: "Tent Theatre",
    city: "Springfield",
    state: "MO",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "TexArts",
    city: "Austin",
    state: "TX",
    audition_page_url: "https://www.tex-arts.org/about/professional-auditions/",
    notes: "",
  },
  {
    name: "Texas Shakespeare Festival",
    city: "Kilgore",
    state: "TX",
    audition_page_url: "http://www.texasshakespeare.com/actors",
    notes: "",
  },
  {
    name: "The Barn Dinner Theatre",
    city: "Greensboro",
    state: "NC",
    audition_page_url: "https://www.barndinner.com/auditions",
    notes: "",
  },
  {
    name: "The Barnstormers Theatre",
    city: "Tamworth",
    state: "NH",
    audition_page_url: "http://www.barnstormerstheater.com/auditions.html",
    notes: "On Backstage",
  },
  {
    name: "The Black Hills Playhouse",
    city: "Custer",
    state: "SD",
    audition_page_url: "https://www.blackhillsplayhouse.com/seasonal-employment",
    notes: "",
  },
  {
    name: "The Candlelight Theatre",
    city: "Wilmington",
    state: "DE",
    audition_page_url: "https://candlelighttheatredelaware.org/auditions/?_gl=1*2xcy3x*_ga*MTM0ODM4MDUzNC4xNjc1NzI1ODY3*_ga_B1B6Y6N0PJ*MTY3NTcyNTg2Ni4xLjAuMTY3NTcyNTg2Ni4wLjAuMA..&_ga=2.106488842.806872598.1675725868-1348380534.1675725867",
    notes: "",
  },
  {
    name: "The Eagle Theatre",
    city: "Hammonton",
    state: "NJ",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "The Firehouse Theatre",
    city: "Farmers Branch",
    state: "TX",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "The Gateway",
    city: "Bellport",
    state: "NY",
    audition_page_url: "https://thegateway.org/Online/default.asp?BOparam::WScontent::loadArticle::permalink=casting&BOparam::WScontent::loadArticle::context_id=&menu_id=5758BEBC-DF40-4AF2-95EC-B887F70C8A34",
    notes: "",
  },
  {
    name: "The Geva Theatre",
    city: "Rochester",
    state: "NY",
    audition_page_url: "https://www.gevatheatre.org/artists/casting/",
    notes: "",
  },
  {
    name: "The Glimmerglass Festival",
    city: "Cooperstown",
    state: "NY",
    audition_page_url: "https://glimmerglass.org/auditions/",
    notes: "",
  },
  {
    name: "The Henegar Center",
    city: "Melbourne",
    state: "FL",
    audition_page_url: "https://henegarcenter.com/auditions/",
    notes: "only a  travel stipend",
  },
  {
    name: "The Legacy Theatre",
    city: "Tyrone",
    state: "GA",
    audition_page_url: "http://www.thelegacytheatre.org/info/auditions.php",
    notes: "",
  },
  {
    name: "The Lexington Theatre Company",
    city: "Lexington",
    state: "KY",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "The Little  Victory Theatre",
    city: "Staten Island",
    state: "NY",
    audition_page_url: "http://www.littlevictorytheatre.com/auditions.html",
    notes: "",
  },
  {
    name: "The Lyric Stage Company of Boston",
    city: "Boston",
    state: "MA",
    audition_page_url: "https://www.lyricstage.com/about/get-involved/auditions/",
    notes: "",
  },
  {
    name: "The Market Theatre",
    city: "Audition — Market Theatre | Anderson",
    state: "SC",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "The Moonlight",
    city: "Vista",
    state: "CA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "The Muny",
    city: "St. Louis",
    state: "MO",
    audition_page_url: "https://muny.org/jobs/",
    notes: "",
  },
  {
    name: "The New Paradigm Theatre Company",
    city: "Stamford",
    state: "CT",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "The North Street Playhouse",
    city: "Onancock",
    state: "VA",
    audition_page_url: "http://northstreetplayhouse.org/auditions",
    notes: "",
  },
  {
    name: "The Palace Theatre",
    city: "Manchester",
    state: "NH",
    audition_page_url: "https://palacetheatre.org/jobs/actors/",
    notes: "",
  },
  {
    name: "The Paul Bunyan Playhouse",
    city: "Bemidji",
    state: "MN",
    audition_page_url: "http://www.thechieftheater.com/audition-information.html",
    notes: "",
  },
  {
    name: "The Playmill Theatre",
    city: "West Yellowstone",
    state: "MT",
    audition_page_url: "https://www.playmill.com/",
    notes: "",
  },
  {
    name: "The Prizery Theatre",
    city: "South Boston",
    state: "VA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "The Public Theatre of San Antonio",
    city: "San Antonio",
    state: "TX",
    audition_page_url: "https://thepublicsa.org/services/auditions/",
    notes: "",
  },
  {
    name: "The Redhouse",
    city: "Syracuse",
    state: "NY",
    audition_page_url: "http://www.theredhouse.org/auditions/",
    notes: "",
  },
  {
    name: "The REV Theatre Company",
    city: "Auburn",
    state: "NY",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "The Stephen Foster Story",
    city: "Bradstown",
    state: "KY",
    audition_page_url: "http://www.stephenfoster.com/auditions/",
    notes: "",
  },
  {
    name: "The Temple Theatre Company",
    city: "Sanford",
    state: "NC",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "The Theatre Lab",
    city: "Dayton",
    state: "OH",
    audition_page_url: "https://www.theatrelabdayton.org/auditions",
    notes: "",
  },
  {
    name: "The Thousand Island Playhouse",
    city: "Gananoque",
    state: "ON",
    audition_page_url: "http://www.1000islandsplayhouse.com/auditions/",
    notes: "Acting Only",
  },
  {
    name: "The Umbrella Arts Center",
    city: "Concord",
    state: "MA",
    audition_page_url: "https://theumbrellaarts.org/performing-arts/theater/auditions-opportunities",
    notes: "",
  },
  {
    name: "The Winter Park Playhouse",
    city: "Winter Park",
    state: "FL",
    audition_page_url: "https://www.winterparkplayhouse.org/GetInvolved.html",
    notes: "",
  },
  {
    name: "Theatre Aspen",
    city: "Aspen",
    state: "CO",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Theatre at the Center",
    city: "Muster",
    state: "IN",
    audition_page_url: "https://www.theatreatthecenter.com/mission-statement/casting",
    notes: "",
  },
  {
    name: "Theatre Raleigh",
    city: "Raleigh",
    state: "NC",
    audition_page_url: "http://www.theatreraleigh.com/about-us/auditions/",
    notes: "",
  },
  {
    name: "Theatre SilCo",
    city: "Silverthorne",
    state: "CO",
    audition_page_url: "http://www.lakedillontheatre.org/join-the-team/auditions/",
    notes: "",
  },
  {
    name: "Theatre Under the Stars",
    city: "Houston",
    state: "TX",
    audition_page_url: "https://www.tuts.com/about/auditions",
    notes: "",
  },
  {
    name: "Theatre West",
    city: "Scottsbluff",
    state: "NE",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Theatre West End",
    city: "Sanford",
    state: "FL",
    audition_page_url: "https://theaterwestend.com/auditions",
    notes: "",
  },
  {
    name: "Theatre West Virginia",
    city: "Beaver",
    state: "WV",
    audition_page_url: "https://www.theatrewestvirginia.org/auditions/",
    notes: "",
  },
  {
    name: "Theatre Winter Haven",
    city: "Winter Haven",
    state: "FL",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Theatre Workshop of Nantucket",
    city: "Nantucket",
    state: "MA",
    audition_page_url: "https://theatrenantucket.org/about/auditions",
    notes: "",
  },
  {
    name: "Thin Air Theatre Company",
    city: "Cripple Creek",
    state: "CO",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Thunder Bay Theatre",
    city: "Alpena",
    state: "MI",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Tibbets Theatre",
    city: "Get Involved | Tibbits Opera House | Coldwater",
    state: "MichiganTibbits",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Timber Lake Playhouse",
    city: "Mt Carroll",
    state: "IL",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Tipping Point Theatre",
    city: "Northville",
    state: "MI",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Titusville Playhouse",
    city: "Titusville",
    state: "FL",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Toby’s Dinner Theatre",
    city: "Columbia",
    state: "MD",
    audition_page_url: "https://tobysdinnertheatre.com/about-us/auditions-employment/",
    notes: "",
  },
  {
    name: "Totem Pole Playhouse",
    city: "Fayetteville",
    state: "PA",
    audition_page_url: "https://totempoleplayhouse.org/about-the-theatre/auditions/",
    notes: "",
  },
  {
    name: "Uptown Players",
    city: "Dallas",
    state: "TX",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Utah Festival",
    city: "Logan",
    state: "UT",
    audition_page_url: "http://www.utahfestival.org/index.php?p_resource=about_auditions",
    notes: "",
  },
  {
    name: "Utah Shakespeare Festival",
    city: "Cedar City",
    state: "UT",
    audition_page_url: "https://www.bard.org/about/employment/",
    notes: "",
  },
  {
    name: "Vero Beach Theatre Guild",
    city: "Vero Beach",
    state: "FL",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Village Theatre",
    city: "Auditions - Village Theatre in Issaquah & Everett",
    state: "WA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Vintage Theatre",
    city: "Aurora",
    state: "CO",
    audition_page_url: "https://www.vintagetheatre.com/auditions/",
    notes: "",
  },
  {
    name: "Virginia Music Theatre",
    city: "Virginia Beach",
    state: "VA",
    audition_page_url: "http://www.vmtheatre.org/index.php/auditions",
    notes: "",
  },
  {
    name: "Virginia Rep Theatre",
    city: "Richmond",
    state: "VA",
    audition_page_url: "http://va-rep.org/auditions.html",
    notes: "",
  },
  {
    name: "Virginia Stage Company",
    city: "Norfolk",
    state: "VA",
    audition_page_url: "https://www.vastage.org/auditions/",
    notes: "",
  },
  {
    name: "Wagon Wheel Theatre",
    city: "Warsaw",
    state: "IN",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Warsaw Federal Incline Theater",
    city: "Cincinnati",
    state: "OH",
    audition_page_url: "http://www.cincinnatilandmarkproductions.com/Incline/Auditions.aspx",
    notes: "No Housing",
  },
  {
    name: "Waterfront Playhouse",
    city: "Key West",
    state: "FL",
    audition_page_url: "https://www.waterfrontplayhouse.org/auditions/auditions/",
    notes: "",
  },
  {
    name: "Weathervane Playhouse",
    city: "Newark",
    state: "OH",
    audition_page_url: "http://www.weathervaneplayhouse.org/index.php/getinvolved/audition",
    notes: "",
  },
  {
    name: "West Virginia Public Theatre",
    city: "Morgantown",
    state: "WV",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Wheelock Family Dinner",
    city: "Boston",
    state: "MA",
    audition_page_url: "https://www.wheelockfamilytheatre.org/auditions/",
    notes: "",
  },
  {
    name: "Wick Theatre",
    city: "Boca Raton",
    state: "FL",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Williamstown  Theatre Festival",
    city: "Williamstown",
    state: "MA",
    audition_page_url: "https://wtfestival.org/work-learn/",
    notes: "",
  },
  {
    name: "Winnipesaukee Playhouse",
    city: "Meredith",
    state: "NH",
    audition_page_url: "http://www.winnipesaukeeplayhouse.org/professional-company-employment.html",
    notes: "",
  },
  {
    name: "Wolfbane Productions",
    city: "Appomattox",
    state: "VA",
    audition_page_url: "https://www.wolfbane.org/auditions/",
    notes: "",
  },
  {
    name: "Woodminster Summer Musicals",
    city: "Oakland",
    state: "CA",
    audition_page_url: null,
    notes: "",
  },
  {
    name: "Woodstock Playhouse",
    city: "Woodstock",
    state: "NY",
    audition_page_url: "http://www.woodstockplayhouse.org/employment--casting",
    notes: "",
  },
  {
    name: "Yorktown Stage",
    city: "Yorktown Heights",
    state: "NY",
    audition_page_url: "https://www.yorktownstage.org/auditions-for-yorktown-stage/",
    notes: "",
  },
  {
    name: "Zach Theatre",
    city: "Austin",
    state: "TX",
    audition_page_url: null,
    notes: "",
  },
];